config/routes.rb
Rails.application.routes.draw do
  get 'credit_card/pay'

  get 'credit_card/return'

  get 'credit_card/turnOff'

  get 'credit_card/turnOn'

  get 'rental/index'

  get 'rental/show/:id' =>"rental#show", :as => 'rental_show'

  devise_for :users

  resources :products do
    get 'page/:page', :action => :index, :on => :collection
  end

  get 'home'        => "page#Home"
  get 'about_us'    => "page#about_us"

  match 'contact_us' => 'page#contact_us', :via => [:post, :get]

  get 'newsletter'  => 'page#newsletter'
  get 'blog'        => 'page#blog'
  get 'calendar(/:year(/:month) )' => 'page#calendar', :as =>'calendar'
  get 'articles'    => 'page#articles'
  get 'login'       => 'page#login'

  get 'dave/teach'

  get 'dave/speak'

  get 'dave/dig'

  get 'say/hello' # =>say#hello
  get 'say/goodbye'
  get 'say/something'

  root 'page#Home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base

  def full_name
      return first_name + ' ' + last_name
  end

  def describe
      return '#{first_name } #{last_name} is #{age} years of age'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base


  validates_presence_of :name
  validates_numericality_of :quantity
  validates_uniqueness_of :name


 # max_paginates_per 5
  paginates_per 5
  def proper_name
    name.titleize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    return first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#class ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credit_card_controller.rb
class CreditCardController < ApplicationController
  def pay
  end

  def return
  end

  def turnOff
  end

  def turnOn
  end
end

app/controllers/dave_controller.rb
class DaveController < ApplicationController
  def teach
  end

  def speak
  end

  def dig
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def Home
  end

  def about_us
  end

  def contact_us
    @form_error = false
    @submitted = params["commit"]
    @name = params["name"]
    if ( @name == "" )
      @error_message = 'Must enter your name!!'
      @form_error = true
    end

    @email = params["email"]
    if ( @email == "" )
      @error_message = 'Must enter your email!!'
      @form_error = true
    end

    @question = params["question"]
    @newsletter = params['newsletter'] == 'newsletter'
    gender = params['gender']
    @male = gender == 'male'
    @female = gender == 'female'
    @product = params['product']
  end

  def products
  end

  def newsletter
  end

  def blog
  end

  def calendar
    @time = Time.now
    @month = params['month'].to_i
    @year = params['year'].to_i

    if( !(@month >= 1 && @month <=12) )
      @month =@time.strftime( "%m").to_i
    end

    if( @year <= 0 )
      @year = @time.strftime("%Y").to_i
    end

  end

  def articles
  end

  def login
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
    @person = Person.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
 # before_filter :authenticate, except: [:index, :show]
  before_filter :authenticate


  # GET /products
  # GET /products.json
  def index
    @page = params['page']
    @products = Product.page(@page).order(:updated_at=>:desc)
    #@prev_page = @page -1 unless @page == 0
    #@next_page = @page +1 unless @page*5 > Product.count
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :cost, :quantity, :image, :comment, :thumbnail)
    end

  private
    def authenticate
      authenticate_user! && current_user.admin?
    end
end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index

    @products = Product.page(@page).order(:updated_at=>:desc)
  end

  def show
    @product = Product.find( params['id'] )
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello

    @now = Time.now

  end

  def goodbye


  end

def something

end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link_to ( click_text, action, url )

      return link_to click_text, url


  end

  def isAdmin?
    return current_user.try(:admin?)
  end
end

app/helpers/credit_card_helper.rb
module CreditCardHelper
end

app/helpers/dave_helper.rb
module DaveHelper
end

app/helpers/page_helper.rb
module PageHelper

  def calendar( month, year )

    prev_month = month - 1
    prev_year = year

    next_month = month + 1
    next_year = year

    if( prev_month <= 0)
      prev_month = 12
      prev_year = year -1
    end

    if( prev_month >= 12 )
      next_month = 1
      next_year = year +1

    end

    current_date  = Date.new(year, month, 1)
    day_of_week   = current_date.strftime("%w").to_i

    cal=""
    cal += "<br/>"
    #cal += link_to "Prev", "/page/calendar?month=#{prev_month }&year=#{prev_year}"

    cal += link_to("Prev", calendar_path(:month=> prev_month, :year => prev_year) )

    cal += "&nbsp"
    cal += current_date.strftime("%B")
    cal += "&nbsp"

    cal += link_to("Next", calendar_path(:month=> next_month, :year => next_year) )
    #cal += link_to "Next", "/page/calendar?month=#{next_month }&year=#{next_year}"


    cal   += "<br/><table border='1'><tr>"
    days  = %w( Sun Mon Tues Weds Thu Fri Sat)


    days.each do | day |
      cal += "<td>#{day}</td>"
    end

    cal += "<tr/>"
    cal += "<tr>"

  #draw calendar - row first week of the month
    day_of_week.times do
      cal += "<td>&nbsp;</td>"
    end

  #draw calendar - Middle columns

  #draw calendar - last row

    # look at Date class, figure out how many days in a month, get last day and minus one



    (7 - day_of_week).times do |day|
      cal += "<td>#{day +1}</td>"
    end


    cal += "</tr></table>"
    cal += "Month: #{month} <br/>"
    cal += "<br/>Year: #{year}"
    cal += "<br/>Date: #{current_date}"
    cal += "<br/>Day of Week: #{day_of_week}"

            return cal
  end


  def show_link ( link )
    return link_to "Google", "http://google.com"
  end


end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/credit_card/pay.html.erb
<h1>CreditCard#pay</h1>
<p>Find me in app/views/credit_card/pay.html.erb</p>

app/views/credit_card/return.html.erb
<h1>CreditCard#return</h1>
<p>Find me in app/views/credit_card/return.html.erb</p>

app/views/credit_card/turnOff.html.erb
<h1>CreditCard#turnOff</h1>
<p>Find me in app/views/credit_card/turnOff.html.erb</p>

app/views/credit_card/turnOn.html.erb
<h1>CreditCard#turnOn</h1>
<p>Find me in app/views/credit_card/turnOn.html.erb</p>

app/views/dave/dig.html.erb
<h1>Dave#dig</h1>
<p>Find me in app/views/dave/dig.html.erb</p>

app/views/dave/speak.html.erb
<h1>Dave#speak</h1>
<p>Find me in app/views/dave/speak.html.erb</p>

app/views/dave/teach.html.erb
<h1>Dave#teach</h1>
<p>Find me in app/views/dave/teach.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "YouTube" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


    <link rel="shortcut icon" href="images/favicon.gif" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="css/styles.css"/>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>












<%= current_user.admin? %>
<%= isAdmin? %>





  </head>

  <body>

  <div class="bg">

    <!--start container-->
    <div id="container">

      <!--start header-->
      <header>

        <!--start menu-->
        <%= render '/shared/nav' %>
        <!--end menu-->



        <!--end header-->
      </header>

      <!--start intro-->
      <section id="intro">
        <hgroup>
          <h1>"Simplicity is the ultimate sophistication"<span>- Leonardo da Vinci</span></h1>
          <h2>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin.
            Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</h2>
        </hgroup>
      </section>
      <!--end intro-->
      <!--start holder-->
      <div class="holder_content">
        <section class="group1">
          <h3>About us</h3>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin.
            Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy.</p>
          <a class="photo_hover3" href="#"><img src="images/picture1.jpg" width="240" height="214" alt="picture1"/></a>
          <a href="#"><span class="button">Read more</span></a>
        </section>
        <section class="group2">
          <h3>Services</h3>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin.
            Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy.</p>
          <a class="photo_hover3" href="#"><img src="images/picture2.jpg" width="240" height="214" alt="picture1"/></a>
          <a href="#"><span class="button">Read more</span></a>
        </section>
        <section class="group3">
          <h3>Latest news</h3>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin.
            Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy.   </p>
          <a class="photo_hover3" href="#"><img src="images/picture3.jpg" width="240" height="214" alt="picture1"/></a>
          <a href="#"><span class="button">Read more</span></a>
        </section>
      </div>
      <!--end holder-->
      <!--start holder-->
      <div class="holder_content">
        <section class="group4">
          <h3>Latest article</h3>
          <article>
            <h4>22.08.2011  - Design to express </h4>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst.</p>










          </article>
        </section>
      </div>










      <div class="holder_content">
        <section class="group1">
          <%= bootstrap_flash %>
          <%= yield %>
        </section>
      </div>












      <!--end holder-->
    </div>
    <!--end container-->

  <div class="container">











  </div>





    <!--start footer-->
    <footer>
      <div class="container">
        <div id="FooterTwo"> © 2015 LAUREN@LAUREN.MN </div>

      </div>
    </footer>
    <!--end footer-->
  </div>
  <!--end bg-->
  <!-- Free template distributed by http://freehtml5templates.com -->

  </body>
</html>

app/views/page/Home.html.erb
<h1>Page#Home</h1>
<p>Find me in app/views/page/Home.html.erb</p>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calendar.html.erb
<h1>Calendar</h1>




#print day of the week
<%= day_of_week = @time.strftime("%w").to_i%>




<!-- Display calendar -->
<%= calendar(@month, @year).html_safe %>

app/views/page/contact_us.html.erb
<h1>Contact Us</h1>

<h2>Your Name is: <%=@name%></h2><br/>
<h2>Your email is: <%=@email%></h2>

<pre>
<% params.each do |key, value| %>
    <%= key + ' ==> ' + value + '\n' %>
    <% end %>
</pre>

<br/>


<% if !@submitted || @form_error %>
    <%=@error_message%>
    <%= form_for contact_us_path, :method => "POST" do %>

        <%= label_tag :name, "Enter your full name: "%><br/>
        <%= text_field_tag :name, @name, :placeholder => "Enter your name", :focus => 'autofocus' %><br/>


        <%= label_tag :email, "Enter your email: "%><br/>
        <%= email_field_tag :email, @email, :placeholder =>'Enter your email' %><br/>

        <%= submit_tag "Ask Question" %><br/>
        <%= text_area_tag :question, @question, :size => '19X15', :placeholder => 'Enter your question'%>
        <br/>Subscribe to my newletter? &nbsp
        <%= check_box_tag :newsletter, 'newsletter', @newsletter %>

        <br/>
        <%= radio_button_tag :gender, 'male', @male %>Male<br/>
        <%= radio_button_tag :gender, 'female', @female %>Female</br>

        <select>
          <option>Call Today</option>
          <option>Call Tomorrow</option>
        </select>

        <br/>
        <%=select_tag :product, options_for_select( [ [ 'Today', 1], ['Tomorrow', 2] ], @product) %>

        <% end %>
    <% else %>
        Thanks for your submission.



<% end %>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

app/views/person/index.html.erb
<h1>Person#index</h1>
<p>Find me in app/views/person/index.html.erb</p>

<% @person.each do |person| %>

    <%= if(person) then person.first_name end%><br/>

<% end %>

app/views/products/_form.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :class =>"tinymce" %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>

    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_field :comment %>
    </div>

    <div class="field">
      <%= f.label :thumbnail %><br>
      <%= f.text_field :thumbnail %>
    </div>

    <div >
      <%= text_area_tag :content, "", :class => "tinymce", :rows => 40, :cols => 120 %>

    </div>

    <div class="actions">

  <%= f.submit %>
</div>
<% end %>

app/views/products/edit.html.erb
<%= tinymce_assets %>
<%= tinymce %>
<h1>Editing Product</h1>


<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
<%= paginate @products %>
<%#= link_to "Previous", products_path(:page=>@prev_page) %>
<%#= link_to "Next", products_path(:page=>@next_page) %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Quantity</th>
      <th>Image</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id%></td>
        <td><%= link_to product.proper_name, product_path(product) %></td>
        <td><%= product.price %></td>
        <td><%= truncate(product.description.html_safe, :length=>20 )%></td>
        <td><%= product.cost %></td>
<td><%= product.quantity %></td>
<td><%= image_tag product.image %></td>
<td><%= link_to (image_tag( product.thumbnail) ), product_path(product) %></td>
<td><%= link_to 'Show', product %></td>

<% if current_user.try(:admin?) %>

    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%end%>
</tr>
<% end %>
</tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

<% if user_signed_in? %>
    Welcome, <%= current_user.full_name %> <br/>
<%end%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.proper_name%>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description.html_safe %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image %>
</p>



<p>
  <strong>Thumbnail:</strong>
  <%= image_tag @product.thumbnail %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @product.comment %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/rental/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
<%= paginate @products %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Image</th>
    <th>Thumbnail</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>

        <td><%= link_to product.proper_name, rental_show_path(product) %></td>
        <td><%= product.price %></td>
        <td><%= truncate(product.description.html_safe, :length=>20 )%></td>

        <td><%= product.quantity %></td>
        <td><%= image_tag product.image %></td>
        <td><%= link_to (image_tag( product.thumbnail) ), rental_show_path(product) %></td>
        <td><%= link_to 'Show', rental_show_path(product.id) %></td>


      </tr>
  <% end %>
  </tbody>
</table>

<br>


<% if user_signed_in? %>
    Welcome, <%= current_user.full_name %> <br/>
    hahah
    hahah
<%end%>

<% isAdmin? %>
<% if isAdmin? %>
    <H1>IMMA ADMIN</H1>
<% end%>

app/views/rental/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.proper_name%>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image %>
</p>



<p>
  <strong>Thumbnail:</strong>
  <%= image_tag @product.thumbnail %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @product.comment %>
</p>


<%= link_to 'Back', rental_index_path %>

app/views/say/goodbye.html.erb
<h1> Goodbye LoLo </h1>

app/views/say/hello.html.erb
<h1>Say#hello</h1>h
<p>Find me in app/views/say/hello.html.erb</p>


<p> <%=@now %></p>
<%= 2+2 %>

<%= link_to "Teach Dave", dave_teach_path %>

<a href="http://www.rubyonrails.org">Ruby on Rails</a>

<%= nav_link_to  "Login", "login", page_login_path %>

app/views/say/something.html.erb
This is say something

app/views/shared/_nav.html.erb
<nav>
  <ul>

    <li> <%= nav_link_to "Home", "home", home_path %></li>
    <li><%=  nav_link_to "About Us","about_us", about_us_path %></li>
    <li><%=  nav_link_to  "Contact Us", "contact_us", contact_us_path %></li>
    <li><%=  nav_link_to  "Articles", "articles", articles_path %></li>

    <li><%=  nav_link_to  "Calendar", "calendar", calendar_path %></li>
    <li><%=  nav_link_to  "Blog", "blog", blog_path %></li>
    <li><%=  nav_link_to  "Products", "products", products_path %></li>
    <li><%=  nav_link_to  "Newsletter", "newsletter", newsletter_path %></li>

    <% if user_signed_in? %>

    <li><%=  link_to "Logout", destroy_user_session_path, :method => :delete %></li>



    <% else %>
        <li><%=  nav_link_to  "Login", "login", new_user_session_path %></li>

    <%end %>

  </ul>
</nav>